name: 'Upload to S3'
description: ''
inputs:

  dirname:
    description: 'folder to upload'
    required: true
    default: ''
     
  bucketname:
    description: 'Bucket name'
    requred: true
    default: ''

  s3dirname:
    description: 'folder on S3 to upload to'
    requred: true
    default: ''
        
  SELECTEL_KEY_ID:
    required: true

  SELECTEL_ACCESS_KEY:
    required: true

  ENDPOINT:
    required: false
    default: https://s3.selcdn.ru
  
  REGION:
    required: false
    default: "ru-1a"

  DOWNLOAD:
    required: false
    default: "false"

  FILENAME:
    required: false
    default: ""

runs:
  using: "composite"
  steps: 
    - name: Configure Selectel
      shell: bash
      run: |
        aws configure set aws_access_key_id "${{ inputs.SELECTEL_KEY_ID }}"
        aws configure set aws_secret_access_key "${{ inputs.SELECTEL_ACCESS_KEY }}" 
        aws configure set endpoint-url ${{ inputs.ENDPOINT }}
        aws configure set default.region ${{ inputs.REGION }}
        aws s3 ls --endpoint https://s3.selcdn.ru/

    - name: Sync with Selectel (UPLOAD)
      if: inputs.DOWNLOAD == 'false'
      shell: bash
      run: |
        ([ -d '${{ inputs.dirname }}' ] && aws s3 sync '${{ inputs.dirname }}' 's3://${{ inputs.bucketname }}/${{ inputs.s3dirname }}' --endpoint ${{ inputs.ENDPOINT }}) || (echo 'Bad path ${{ inputs.dirname }}')

    - name: Sync with Selectel (DOWNLOAD)
      if: inputs.DOWNLOAD == 'true' && inputs.FILENAME == ''
      shell: bash
      run: |
        aws s3 sync 's3://${{ inputs.bucketname }}/${{ inputs.s3dirname }}' '${{ inputs.dirname }}' --endpoint ${{ inputs.ENDPOINT }}

    - name: Copy from Selectel (DOWNLOAD)
      if: inputs.DOWNLOAD == 'true' && inputs.FILENAME != ''
      shell: bash
      run: |
        aws s3 cp 's3://${{ inputs.bucketname }}/${{ inputs.s3dirname }}/${{ inputs.FILENAME }}' '${{ inputs.dirname }}/${{ inputs.FILENAME }}' --endpoint ${{ inputs.ENDPOINT }}

    # - name: Print URLs 
    #   if: inputs.URL-PREFIX != 'None' && inputs.DOWNLOAD == 'false'
    #   shell: bash
    #   run: |
    #     echo ${{ inputs.URL-PREFIX }}${{ inputs.bucketname }}/${{ inputs.s3dirname }}/filename
    #     echo will be later
